---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mydeploy-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
        - name: cont-1
          image: nginx
          ports:
            - containerPort: 80
